# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5d3ea0756ca8cc28a5471352e42a1b61"
name = "Test app"
handle = "test-app-12288"
application_url = "https://quiet-honey-lands-advert.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://quiet-honey-lands-advert.trycloudflare.com/auth/callback", "https://quiet-honey-lands-advert.trycloudflare.com/auth/shopify/callback", "https://quiet-honey-lands-advert.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
